Always save test logs

diff --git a/.github/actions/gradle-build/action.yml b/.github/actions/gradle-build/action.yml
--- a/.github/actions/gradle-build/action.yml
+++ b/.github/actions/gradle-build/action.yml
@@ -92,13 +92,19 @@ runs:
         echo "==============="
       shell: bash
 
-    - name: Upload Test Report
-      uses: actions/upload-artifact@v4
-      if: always() # Upload even if tests fail
-      with:
-          name: junit-test-results
-          path: build/reports/tests/test/
+    - name: Create Text Summary of Failures
+      if: failure()
+      run: |
+        # Find all XML result files and extract the failure messages into a txt file
+        grep -hR "failure message" build/test-results/test/*.xml > test-failures.txt || echo "No failures found" > test-failures.txt
+      shell: bash
 
+    - name: Upload Text Report
+      uses: actions/upload-artifact@v4
+      if: always()
+      with:
+        name: test-failures-text
+        path: test-failures.txt
     - name: Upload Artifact
       id: upload
       uses: actions/upload-artifact@v4
